name: 'Deployment for AI'
description: 'Deploy AI to target server'
inputs:
  branch:
    description: 'Target branch'
    required: true
  server-secret:
    description: 'server secret fot ssh'
    required: true
  server-ip:
    description: 'server ip address'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ inputs.server-secret }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no admin@${{ inputs.server-ip }} 'bash -s'  << EOF
        set -e
        echo "Heliaa Deployment script for AI"
        echo "===================================="
        cd /var/www/docker
        docker compose down
        sudo rm -rf app
        git clone git@github.com:Heliaa-PT-Digital-Asia/AI-Model-serving.git -b ${{ inputs.branch }} app
        cd /var/www/docker
        echo "Cleaning up..."
        docker system prune -f
        docker network prune -f
        echo "Bring server back..."
        docker compose up -d
        EOF
      shell: bash
